services:
  back-end:
    #Uncomment the following line to build the image from the Dockerfile
    #build: .
    #Comment the following line if you uncomment the previous line
    image: woudisnakes/portfolio-2023-back:latest
    ports:
      - 3001:3001
      - 9229:9229
    volumes:
      - ./:/usr/src/app
    container_name: back-end
    env_file: .env
    environment:
      - PORT=${PORT}
      - HOST=db
      - DBUSER=${DBUSER}
      - DATABASE=${DATABASE}
      - DBPORT=${DBPORT}
      - DB_RANDOM_TABLE_NAME=${DB_RANDOM_TABLE_NAME}
      - DB_RANDOM_TABLE_NAME_JSON_FILE=${DB_RANDOM_TABLE_NAME_JSON_FILE}
      - FRONT_END_URL=${FRONT_END_URL}
      - PASSWORD_FILE=/run/secrets/password
    secrets:
      - password
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    restart: always
    container_name: db
    env_file: .env
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_INIT_SCRIPTS=/docker-entrypoint-initdb.d/init.sql
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD_FILE=/run/secrets/password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root"]
      interval: 10s
      timeout: 10s
      retries: 10
    secrets:
      - mysql_root_password
      - password

volumes:
  mysql_data:

secrets:
  password:
    file: password.txt
  mysql_root_password:
    file: mysql_root_password.txt
